
import {
  Users,
  User,
  FileText,
  Building,
  List,
  Home,
  DoorOpen,
  FileSignature,
  DollarSign,
  Book,
  BookOpen,
  Landmark,
  Receipt,
  Wrench,
  Ticket,
  FilePieChart,
  Package,
  Settings,
  UserLock,
  Shuffle,
  Building2,
  LayoutDashboard,
  LucideIcon,
  UserTie,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  user: User,
  fileText: FileText,
  building: Building,
  list: List,
  home: Home,
  doorOpen: DoorOpen,
  fileSignature: FileSignature,
  userTie: UserTie,
  dollarSign: DollarSign,
  book: Book,
  bookOpen: BookOpen,
  landmark: Landmark,
  receipt: Receipt,
  wrench: Wrench,
  ticket: Ticket,
  filePieChart: FilePieChart,
  package: Package,
  settings: Settings,
  userLock: UserLock,
  shuffle: Shuffle,
  building2: Building2,
};
